name: living_map
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.1.0
  utf: ^0.9.0
  image: ^3.0.8
  #json_serializable: ^5.0.2

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
  build_runner: ^1.6.2
  build_web_compilers: ^2.12.0
  #widgets: ^1.0.0
